language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_7cab1cb271a0_key -iv $encrypted_7cab1cb271a0_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2202d50bb4c3e230c909
    on_success: change
    on_failure: always
    on_start: never
